# Notes
* **data1-4** are portions of the raw dataset (>2.5m entries).
* **training** and **testing** are smaller, pre-cleaned portions of the raw dataset (~175k and ~82k entries respectively).
* **ground truth** is a label generator for the raw dataset, which can be used to convert data1-4 into new train-test instances.
* **summarize_dataframe** displays important values from the inputted dataframe, such as #rows, #columns, missing values, duplicated entries, distribution of attacks vs normal entries (1 = attack, 0 = normal), and distribution of attack types (DoS, Backdoor, Worms, etc.).

# Setup Imports, Datasets, and Dataframes

In [29]:
# Imports
import kagglehub
import os

import pandas as pd

from sklearn.preprocessing import StandardScaler

In [ ]:
# Download UNSW-NB15 Dataset
path = kagglehub.dataset_download("freshersstaff/unsw-nb15-dataset")

In [38]:
# Load CSV files
raw_data1 = pd.read_csv('/root/.cache/kagglehub/datasets/freshersstaff/unsw-nb15-dataset/versions/1/UNSW-NB15_c/UNSW-NB15_1.csv', header=None)
raw_data2 = pd.read_csv('/root/.cache/kagglehub/datasets/freshersstaff/unsw-nb15-dataset/versions/1/UNSW-NB15_c/UNSW-NB15_2.csv', header=None)
raw_data3 = pd.read_csv('/root/.cache/kagglehub/datasets/freshersstaff/unsw-nb15-dataset/versions/1/UNSW-NB15_c/UNSW-NB15_3.csv', header=None)
raw_data4 = pd.read_csv('/root/.cache/kagglehub/datasets/freshersstaff/unsw-nb15-dataset/versions/1/UNSW-NB15_c/UNSW-NB15_4.csv', header=None)
# Note: Training and Testing datasets are mislabeled!
raw_testing = pd.read_csv('/root/.cache/kagglehub/datasets/freshersstaff/unsw-nb15-dataset/versions/1/UNSW-NB15_c/UNSW_NB15_training-set.csv')
raw_training = pd.read_csv('/root/.cache/kagglehub/datasets/freshersstaff/unsw-nb15-dataset/versions/1/UNSW-NB15_c/UNSW_NB15_testing-set.csv')
raw_gt = pd.read_csv('/root/.cache/kagglehub/datasets/freshersstaff/unsw-nb15-dataset/versions/1/UNSW-NB15_c/NUSW-NB15_GT.csv')

# Combine raw_data1-4 into a single DataFrame
raw_data_full = pd.concat([raw_data1, raw_data2, raw_data3, raw_data4], ignore_index=True)

# Display the first 5 rows of each file
print("\n--- Raw Data 1-4 Head ---")
display(raw_data_full.head())
print("\n--- Raw Training Head ---")
display(raw_training.head())
print("\n--- Raw Testing Head ---")
display(raw_testing.head())
print("\n--- Raw Ground Truth Head ---")
display(raw_gt.head())

/tmp/ipykernel_43111/1011479598.py:2: DtypeWarning: Columns (1,3,47) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data1 = pd.read_csv('/root/.cache/kagglehub/datasets/freshersstaff/unsw-nb15-dataset/versions/1/UNSW-NB15_c/UNSW-NB15_1.csv', header=None)
/tmp/ipykernel_43111/1011479598.py:3: DtypeWarning: Columns (3,39,47) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data2 = pd.read_csv('/root/.cache/kagglehub/datasets/freshersstaff/unsw-nb15-dataset/versions/1/UNSW-NB15_c/UNSW-NB15_2.csv', header=None)

--- Raw Data 1-4 Head ---

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,NaN,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0

--- Raw Training Head ---

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.121478,tcp,-,FIN,6,4,258,172,74.087490,...,1,1,0,0,0,1,1,0,Normal,0
1,2,0.649902,tcp,-,FIN,14,38,734,42014,78.473372,...,1,2,0,0,0,1,6,0,Normal,0
2,3,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,...,1,3,0,0,0,2,6,0,Normal,0
3,4,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,...,1,3,1,1,0,2,1,0,Normal,0
4,5,0.449454,tcp,-,FIN,10,6,534,268,33.373826,...,1,40,0,0,0,2,39,0,Normal,0

--- Raw Testing Head ---

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.000011,udp,-,INT,2,0,496,0,90909.0902,...,1,2,0,0,0,1,2,0,Normal,0
1,2,0.000008,udp,-,INT,2,0,1762,0,125000.0003,...,1,2,0,0,0,1,2,0,Normal,0
2,3,0.000005,udp,-,INT,2,0,1068,0,200000.0051,...,1,3,0,0,0,1,3,0,Normal,0
3,4,0.000006,udp,-,INT,2,0,900,0,166666.6608,...,1,3,0,0,0,2,3,0,Normal,0
4,5,0.000010,udp,-,INT,2,0,2126,0,100000.0025,...,1,3,0,0,0,2,3,0,Normal,0

--- Raw Ground Truth Head ---

,Start time,Last time,Attack category,Attack subcategory,Protocol,Source IP,Source Port,Destination IP,Destination Port,Attack Name,Attack Reference,.
0,1421927414,1421927416,Reconnaissance,HTTP,tcp,175.45.176.0,13284,149.171.126.16,80,Domino Web Server Database Access: /doladmin.n...,-,.
1,1421927415,1421927415,Exploits,Unix 'r' Service,udp,175.45.176.3,21223,149.171.126.18,32780,Solaris rwalld Format String Vulnerability (ht...,CVE 2002-0573 (http://cve.mitre.org/cgi-bin/cv...,.
2,1421927416,1421927416,Exploits,Browser,tcp,175.45.176.2,23357,149.171.126.16,80,Windows Metafile (WMF) SetAbortProc() Code Exe...,CVE 2005-4560 (http://cve.mitre.org/cgi-bin/cv...,.
3,1421927417,1421927417,Exploits,Miscellaneous Batch,tcp,175.45.176.2,13792,149.171.126.16,5555,HP Data Protector Backup (https://strikecenter...,CVE 2011-1729 (http://cve.mitre.org/cgi-bin/cv...,.
4,1421927418,1421927418,Exploits,Cisco IOS,tcp,175.45.176.2,26939,149.171.126.10,80,Cisco IOS HTTP Authentication Bypass Level 64 ...,CVE 2001-0537 (http://cve.mitre.org/cgi-bin/cv...,.

In [36]:
def summarize_dataframe(df: pd.DataFrame) -> dict:
    """Create a compact profile that is useful for first-pass exploration."""
    label_counts = df["label"].value_counts(dropna=False).to_dict() if "label" in df.columns else {}
    attack_counts = df["attack_cat"].value_counts(dropna=False).to_dict() if "attack_cat" in df.columns else {}

    return {
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "missing_values_per_column": df.isna().sum().sort_values(ascending=False).to_dict(),
        "duplicate_rows": int(df.duplicated().sum()),
        "label_distribution": label_counts,
        "attack_category_distribution": attack_counts,
    }

In [37]:
# Call summarize_dataframe for all dataframes
print("\n--- Raw Data 1-4 Summary ---")
display(summarize_dataframe(raw_data_full))

print("\n--- Raw Training Summary ---")
display(summarize_dataframe(raw_training))

print("\n--- Raw Testing Summary ---")
display(summarize_dataframe(raw_testing))

print("\n--- Raw Ground Truth Summary ---")
display(summarize_dataframe(raw_gt))

--- Raw Data 1-4 Summary ---

{'rows': 2540047,
 'columns': 49,
 'missing_values_per_column': {47: 2218764,
  38: 1429879,
  37: 1348145,
  1: 0,
  4: 0,
  5: 0,
  2: 0,
  3: 0,
  8: 0,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  13: 0,
  6: 0,
  7: 0,
  0: 0,
  16: 0,
  15: 0,
  14: 0,
  17: 0,
  21: 0,
  18: 0,
  19: 0,
  20: 0,
  25: 0,
  26: 0,
  27: 0,
  28: 0,
  29: 0,
  22: 0,
  23: 0,
  24: 0,
  32: 0,
  31: 0,
  30: 0,
  33: 0,
  36: 0,
  35: 0,
  39: 0,
  34: 0,
  40: 0,
  41: 0,
  43: 0,
  42: 0,
  44: 0,
  45: 0,
  46: 0,
  48: 0},
 'duplicate_rows': 480630,
 'label_distribution': {},
 'attack_category_distribution': {}}

--- Raw Training Summary ---

{'rows': 175341,
 'columns': 45,
 'missing_values_per_column': {'id': 0,
  'dur': 0,
  'proto': 0,
  'service': 0,
  'state': 0,
  'spkts': 0,
  'dpkts': 0,
  'sbytes': 0,
  'dbytes': 0,
  'rate': 0,
  'sttl': 0,
  'dttl': 0,
  'sload': 0,
  'dload': 0,
  'sloss': 0,
  'dloss': 0,
  'sinpkt': 0,
  'dinpkt': 0,
  'sjit': 0,
  'djit': 0,
  'swin': 0,
  'stcpb': 0,
  'dtcpb': 0,
  'dwin': 0,
  'tcprtt': 0,
  'synack': 0,
  'ackdat': 0,
  'smean': 0,
  'dmean': 0,
  'trans_depth': 0,
  'response_body_len': 0,
  'ct_srv_src': 0,
  'ct_state_ttl': 0,
  'ct_dst_ltm': 0,
  'ct_src_dport_ltm': 0,
  'ct_dst_sport_ltm': 0,
  'ct_dst_src_ltm': 0,
  'is_ftp_login': 0,
  'ct_ftp_cmd': 0,
  'ct_flw_http_mthd': 0,
  'ct_src_ltm': 0,
  'ct_srv_dst': 0,
  'is_sm_ips_ports': 0,
  'attack_cat': 0,
  'label': 0},
 'duplicate_rows': 0,
 'label_distribution': {1: 119341, 0: 56000},
 'attack_category_distribution': {'Normal': 56000,
  'Generic': 40000,
  'Exploits': 33393,
  'Fuzzers': 18184,
  'DoS': 12264,
  'Reconnaissance': 10491,
  'Analysis': 2000,
  'Backdoor': 1746,
  'Shellcode': 1133,
  'Worms': 130}}

--- Raw Testing Summary ---

{'rows': 82332,
 'columns': 45,
 'missing_values_per_column': {'id': 0,
  'dur': 0,
  'proto': 0,
  'service': 0,
  'state': 0,
  'spkts': 0,
  'dpkts': 0,
  'sbytes': 0,
  'dbytes': 0,
  'rate': 0,
  'sttl': 0,
  'dttl': 0,
  'sload': 0,
  'dload': 0,
  'sloss': 0,
  'dloss': 0,
  'sinpkt': 0,
  'dinpkt': 0,
  'sjit': 0,
  'djit': 0,
  'swin': 0,
  'stcpb': 0,
  'dtcpb': 0,
  'dwin': 0,
  'tcprtt': 0,
  'synack': 0,
  'ackdat': 0,
  'smean': 0,
  'dmean': 0,
  'trans_depth': 0,
  'response_body_len': 0,
  'ct_srv_src': 0,
  'ct_state_ttl': 0,
  'ct_dst_ltm': 0,
  'ct_src_dport_ltm': 0,
  'ct_dst_sport_ltm': 0,
  'ct_dst_src_ltm': 0,
  'is_ftp_login': 0,
  'ct_ftp_cmd': 0,
  'ct_flw_http_mthd': 0,
  'ct_src_ltm': 0,
  'ct_srv_dst': 0,
  'is_sm_ips_ports': 0,
  'attack_cat': 0,
  'label': 0},
 'duplicate_rows': 0,
 'label_distribution': {1: 45332, 0: 37000},
 'attack_category_distribution': {'Normal': 37000,
  'Generic': 18871,
  'Exploits': 11132,
  'Fuzzers': 6062,
  'DoS': 4089,
  'Reconnaissance': 3496,
  'Analysis': 677,
  'Backdoor': 583,
  'Shellcode': 378,
  'Worms': 44}}

--- Raw Ground Truth Summary ---

{'rows': 174347,
 'columns': 12,
 'missing_values_per_column': {'Attack Reference': 50638,
  'Attack subcategory': 4097,
  'Attack Name': 1,
  'Start time': 0,
  'Attack category': 0,
  'Last time': 0,
  'Protocol': 0,
  'Source IP': 0,
  'Destination IP': 0,
  'Source Port': 0,
  'Destination Port': 0,
  '.': 0},
 'duplicate_rows': 6,
 'label_distribution': {},
 'attack_category_distribution': {}}

# Preprocess Training / Testing Data

In [39]:
# Perform ordinal and one-hot encoding on non-numeric features:
# > Ordinal encoding is applied to proto.
# > One-hot encoding is applied to service, state, and attack_cat.

# Copy data for preprocessing
encoded_training = raw_training.copy()
encoded_testing = raw_testing.copy()

# Ordinal Encoding.
# > pd.factorize() is used since there is no explicit hierarchy (uses only the indexes).
encoded_training['proto'] = pd.factorize(encoded_training['proto'])[0]
encoded_testing['proto'] = pd.factorize(encoded_testing['proto'])[0]

# One-Hot Encoding
encoded_training = pd.get_dummies(encoded_training, columns=['service', 'state', 'attack_cat'], drop_first=True)
encoded_testing = pd.get_dummies(encoded_testing, columns=['service', 'state', 'attack_cat'], drop_first=True)

# Reindex training-testing due to #columns mismatch after encoding.
columns = list(set(encoded_training.columns) | set(encoded_testing.columns))
encoded_training = encoded_training.reindex(columns=columns, fill_value=0)
encoded_testing = encoded_testing.reindex(columns=columns, fill_value=0)

print("\n--- Encoded Training Head ---")
display(encoded_training.head())

print("\n--- Encoded Testing Head ---")
display(encoded_testing.head())

--- Encoded Training Head ---

,state_REQ,ct_ftp_cmd,ct_src_ltm,sinpkt,dttl,state_no,ct_dst_sport_ltm,dmean,state_FIN,dload,...,sjit,state_CON,attack_cat_Shellcode,smean,state_PAR,attack_cat_Generic,spkts,service_pop3,service_ftp-data,service_http
0,False,0,1,24.295600,254,False,1,43,True,8495.365234,...,30.177547,0,False,43,False,False,6,False,False,False
1,False,0,1,49.915000,252,False,1,1106,True,503571.312500,...,61.426934,0,False,52,False,False,14,False,False,False
2,False,0,2,231.875571,252,False,1,824,True,60929.230470,...,17179.586860,0,False,46,False,False,8,False,False,False
3,False,1,2,152.876547,252,False,1,64,True,3358.622070,...,259.080172,0,False,52,False,False,12,False,False,False
4,False,0,2,47.750333,252,False,1,45,True,3987.059814,...,2415.837634,0,False,53,False,False,10,False,False,False

--- Encoded Testing Head ---

,state_REQ,ct_ftp_cmd,ct_src_ltm,sinpkt,dttl,state_no,ct_dst_sport_ltm,dmean,state_FIN,dload,...,sjit,state_CON,attack_cat_Shellcode,smean,state_PAR,attack_cat_Generic,spkts,service_pop3,service_ftp-data,service_http
0,False,0,1,0.011,0,0,1,0,False,0.0,...,0.0,False,False,248,0,False,2,False,False,False
1,False,0,1,0.008,0,0,1,0,False,0.0,...,0.0,False,False,881,0,False,2,False,False,False
2,False,0,1,0.005,0,0,1,0,False,0.0,...,0.0,False,False,534,0,False,2,False,False,False
3,False,0,2,0.006,0,0,1,0,False,0.0,...,0.0,False,False,450,0,False,2,False,False,False
4,False,0,2,0.010,0,0,1,0,False,0.0,...,0.0,False,False,1063,0,False,2,False,False,False

In [40]:
# Perform standardization using StandardScaler

# Identify numeric columns
numeric_train_columns = encoded_training.select_dtypes(include=['number']).columns.tolist()
numeric_test_columns = encoded_testing.select_dtypes(include=['number']).columns.tolist()

# Filter out 'label' column (since this is the target var)
numeric_train_columns.remove('label')
numeric_test_columns.remove('label')

# Filter out one-hot encoded columns (since these are boolean 0-1)
# > Loop through the numeric columns, determining which need to be dropped.
# > Drop columns AFTER these loops to prevent indexing issues.
remove_train_columns = []
remove_test_columns = []

for col in numeric_train_columns:
    if col.startswith('service_') or col.startswith('state_') or col.startswith('attack_cat_'):
        remove_train_columns.append(col)
for col in numeric_test_columns:
    if col.startswith('service_') or col.startswith('state_') or col.startswith('attack_cat_'):
        remove_test_columns.append(col)

for col in remove_train_columns:
    numeric_train_columns.remove(col)
for col in remove_test_columns:
    numeric_test_columns.remove(col)

# Scale train-test data
scaler = StandardScaler()
encoded_training[numeric_train_columns] = scaler.fit_transform(encoded_training[numeric_train_columns]) # Fit & transform
encoded_testing[numeric_test_columns] = scaler.transform(encoded_testing[numeric_test_columns])         # Transform only

print("\n--- Scaled Training Head ---")
display(encoded_training.head())

print("\n--- Scaled Testing Head ---")
display(encoded_testing.head())

--- Scaled Training Head ---

,state_REQ,ct_ftp_cmd,ct_src_ltm,sinpkt,dttl,state_no,ct_dst_sport_ltm,dmean,state_FIN,dload,...,sjit,state_CON,attack_cat_Shellcode,smean,state_PAR,attack_cat_Generic,spkts,service_pop3,service_ftp-data,service_http
0,False,-0.118590,-0.715714,-0.132788,1.578100,False,-0.554373,-0.314240,True,-0.273700,...,-0.109997,0,False,-0.458048,False,False,-0.104456,False,False,False
1,False,-0.118590,-0.715714,-0.129251,1.560002,False,-0.554373,3.800869,True,-0.069233,...,-0.109302,0,False,-0.414076,False,False,-0.046014,False,False,False
2,False,-0.118590,-0.595543,-0.104126,1.560002,False,-0.554373,2.709185,True,-0.252044,...,0.271392,0,False,-0.443391,False,False,-0.089845,False,False,False
3,False,7.814915,-0.595543,-0.115034,1.560002,False,-0.554373,-0.232945,True,-0.275821,...,-0.104906,0,False,-0.414076,False,False,-0.060624,False,False,False
4,False,-0.118590,-0.595543,-0.129549,1.560002,False,-0.554373,-0.306498,True,-0.275561,...,-0.056942,0,False,-0.409190,False,False,-0.075235,False,False,False

--- Scaled Testing Head ---

,state_REQ,ct_ftp_cmd,ct_src_ltm,sinpkt,dttl,state_no,ct_dst_sport_ltm,dmean,state_FIN,dload,...,sjit,state_CON,attack_cat_Shellcode,smean,state_PAR,attack_cat_Generic,spkts,service_pop3,service_ftp-data,service_http
0,False,-0.11859,-0.715714,-0.136141,-0.720406,0,-0.554373,-0.480703,False,-0.277208,...,-0.110668,False,False,0.543531,0,False,-0.133677,False,False,False
1,False,-0.11859,-0.715714,-0.136142,-0.720406,0,-0.554373,-0.480703,False,-0.277208,...,-0.110668,False,False,3.636212,0,False,-0.133677,False,False,False
2,False,-0.11859,-0.715714,-0.136142,-0.720406,0,-0.554373,-0.480703,False,-0.277208,...,-0.110668,False,False,1.940856,0,False,-0.133677,False,False,False
3,False,-0.11859,-0.595543,-0.136142,-0.720406,0,-0.554373,-0.480703,False,-0.277208,...,-0.110668,False,False,1.530453,0,False,-0.133677,False,False,False
4,False,-0.11859,-0.595543,-0.136141,-0.720406,0,-0.554373,-0.480703,False,-0.277208,...,-0.110668,False,False,4.525419,0,False,-0.133677,False,False,False

# Feature Selection

In [43]:
# Copy data for feature selection
fs_training = encoded_training.copy()
fs_testing = encoded_testing.copy()

# Drop 'id' column (since this is just the index)
fs_training = fs_training.drop('id', axis=1)
fs_testing = fs_testing.drop('id', axis=1)

print("\n--- Training Head w/o id ---")
display(fs_training.head())

print("\n--- Testing Head w/o id ---")
display(fs_testing.head())

--- Training Head w/o id ---

,state_REQ,ct_ftp_cmd,ct_src_ltm,sinpkt,dttl,state_no,ct_dst_sport_ltm,dmean,state_FIN,dload,...,sjit,state_CON,attack_cat_Shellcode,smean,state_PAR,attack_cat_Generic,spkts,service_pop3,service_ftp-data,service_http
0,False,-0.118590,-0.715714,-0.132788,1.578100,False,-0.554373,-0.314240,True,-0.273700,...,-0.109997,0,False,-0.458048,False,False,-0.104456,False,False,False
1,False,-0.118590,-0.715714,-0.129251,1.560002,False,-0.554373,3.800869,True,-0.069233,...,-0.109302,0,False,-0.414076,False,False,-0.046014,False,False,False
2,False,-0.118590,-0.595543,-0.104126,1.560002,False,-0.554373,2.709185,True,-0.252044,...,0.271392,0,False,-0.443391,False,False,-0.089845,False,False,False
3,False,7.814915,-0.595543,-0.115034,1.560002,False,-0.554373,-0.232945,True,-0.275821,...,-0.104906,0,False,-0.414076,False,False,-0.060624,False,False,False
4,False,-0.118590,-0.595543,-0.129549,1.560002,False,-0.554373,-0.306498,True,-0.275561,...,-0.056942,0,False,-0.409190,False,False,-0.075235,False,False,False

--- Testing Head w/o id ---

,state_REQ,ct_ftp_cmd,ct_src_ltm,sinpkt,dttl,state_no,ct_dst_sport_ltm,dmean,state_FIN,dload,...,sjit,state_CON,attack_cat_Shellcode,smean,state_PAR,attack_cat_Generic,spkts,service_pop3,service_ftp-data,service_http
0,False,-0.11859,-0.715714,-0.136141,-0.720406,0,-0.554373,-0.480703,False,-0.277208,...,-0.110668,False,False,0.543531,0,False,-0.133677,False,False,False
1,False,-0.11859,-0.715714,-0.136142,-0.720406,0,-0.554373,-0.480703,False,-0.277208,...,-0.110668,False,False,3.636212,0,False,-0.133677,False,False,False
2,False,-0.11859,-0.715714,-0.136142,-0.720406,0,-0.554373,-0.480703,False,-0.277208,...,-0.110668,False,False,1.940856,0,False,-0.133677,False,False,False
3,False,-0.11859,-0.595543,-0.136142,-0.720406,0,-0.554373,-0.480703,False,-0.277208,...,-0.110668,False,False,1.530453,0,False,-0.133677,False,False,False
4,False,-0.11859,-0.595543,-0.136141,-0.720406,0,-0.554373,-0.480703,False,-0.277208,...,-0.110668,False,False,4.525419,0,False,-0.133677,False,False,False